/* AD30 members - video LESSONS added by group leaders on admin.html ("Add a lesson").
   Loaded on index.html (full timeline), simple.html and admin.html. Plain ES5 for older iPhones.

   Safety rules:
   * Everything a leader types is shown with AD30.esc() / textContent - never as HTML.
   * A video is only embedded when its id passes a strict 11-character check (ID_RE).
   * Scripture is never typed here and never taken from the database: verse text comes only from the
     checked KJV files in kjv/NN.json (one file per book, loaded only when a lesson with references is
     shown). A reference that can't be found is shown as the reference only - never paraphrased.
   * If the lessons table is missing or the request fails, nothing is shown and nothing breaks:
     members never see an error. */
(function () {
  "use strict";
  var AD30 = window.AD30 || {};
  var esc = AD30.esc || function (s) { return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); };
  var L = (window.AD30L = {});

  /*MARKERS-BEGIN (generated by tools/lessons/build_markers.py from index.html)*/
  var MARKERS = [
  {
  "id": "birth",
  "sec": "Before the ministry · 5 BC – 4 BC",
  "dt": "Mon 11 Sep 5 BC (Julian)",
  "ttl": "The birth, placed on the Day of Atonement"
  },
  {
  "id": "herod",
  "sec": "Before the ministry · 5 BC – 4 BC",
  "dt": "4 BC (the guide gives the year only)",
  "ttl": "Herod the Great dies: the upper bound"
  },
  {
  "id": "pilate",
  "sec": "Two men turn thirty · AD 26",
  "dt": "AD 26 (year only)",
  "ttl": "Rulers on the line: Luke 3:1–2’s “fence”"
  },
  {
  "id": "john30",
  "sec": "Two men turn thirty · AD 26",
  "dt": "Mon 18 Mar AD 26",
  "ttl": "John the Baptist reaches thirty; “the word of God came unto John”"
  },
  {
  "id": "jordan",
  "sec": "Two men turn thirty · AD 26",
  "dt": "Wed 11 Sep AD 26",
  "ttl": "The Jordan: “about thirty years of age”"
  },
  {
  "id": "jn1",
  "sec": "Two men turn thirty · AD 26",
  "dt": "Not before about Mon 21 Oct AD 26",
  "ttl": "John 1:29 → 2:1: “the next day” … “the third day”"
  },
  {
  "id": "pass27",
  "sec": "First Passover, one winter, an unnamed feast · AD 27 – AD 28",
  "dt": "Wed 9 Apr AD 27 (fixed calendar)",
  "ttl": "First Passover of the ministry, and “forty and six years”"
  },
  {
  "id": "jn435",
  "sec": "First Passover, one winter, an unnamed feast · AD 27 – AD 28",
  "dt": "About Kislev–Tevet AM 3788 (≈ late Nov AD 27 – Jan AD 28)",
  "ttl": "“Yet four months, and then cometh harvest”: the one winter"
  },
  {
  "id": "jn51",
  "sec": "First Passover, one winter, an unnamed feast · AD 27 – AD 28",
  "dt": "Unknown; AD 28 on the guide’s frame",
  "ttl": "John 5:1: “a feast of the Jews” (unnamed; debated)"
  },
  {
  "id": "pass28",
  "sec": "First Passover, one winter, an unnamed feast · AD 27 – AD 28",
  "dt": "Mon 29 Mar AD 28 (fixed calendar)",
  "ttl": "The Passover John does not name (the guide’s fourth)"
  },
  {
  "id": "pass29",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Sat 16 Apr AD 29 (fixed calendar)",
  "ttl": "“The passover … was nigh”: the five thousand, and the last twelve months"
  },
  {
  "id": "bday33",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Thu 6 Oct AD 29",
  "ttl": "His 33rd birthday on the guide’s reckoning"
  },
  {
  "id": "half",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Tue 11 Oct AD 29 → Wed 5 Apr AD 30",
  "ttl": "The seventh and last half-year: 176 days from Tabernacles to the cross"
  },
  {
  "id": "tab29",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Tue 11 Oct AD 29 (fixed calendar)",
  "ttl": "“The Jews’ feast of tabernacles was at hand”"
  },
  {
  "id": "jn714",
  "sec": "The final twelve months begin · AD 29",
  "dt": "About Fri 14 Oct AD 29, ending at sunset",
  "ttl": "“About the midst of the feast Jesus went up into the temple”"
  },
  {
  "id": "jn737",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Mon 17 Oct AD 29 (fixed calendar)",
  "ttl": "“In the last day, that great day of the feast”: rivers of living water"
  },
  {
  "id": "jn82",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Tue 18 Oct AD 29 (the next day, on the video’s reading)",
  "ttl": "“With his finger wrote on the ground”"
  },
  {
  "id": "ded29",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Mon 19 Dec AD 29 (fixed calendar)",
  "ttl": "“The feast of the dedication, and it was winter”"
  },
  {
  "id": "fig",
  "sec": "The final twelve months begin · AD 29",
  "dt": "Undated (plotted here only for illustration)",
  "ttl": "The fig tree: “these three years … this year also”"
  },
  {
  "id": "jn1155",
  "sec": "The final week",
  "dt": "Early Nisan AD 30 (“nigh at hand”)",
  "ttl": "“The Jews’ passover was nigh at hand”: the last Passover"
  },
  {
  "id": "jn121",
  "sec": "The final week",
  "dt": "Thu 30 Mar AD 30",
  "ttl": "“Six days before the passover came to Bethany”"
  },
  {
  "id": "entry",
  "sec": "The final week",
  "dt": "Fri 31 Mar AD 30",
  "ttl": "The entry: “the lamb fetched before the tenth opens”"
  },
  {
  "id": "n10",
  "sec": "The final week",
  "dt": "Sat 1 Apr AD 30 (from sunset Fri)",
  "ttl": "The lamb set apart: 10 Nisan (the watch)"
  },
  {
  "id": "jn131",
  "sec": "The final week",
  "dt": "Tue 4 Apr AD 30, after sunset",
  "ttl": "“Before the feast of the passover”: the last supper night"
  },
  {
  "id": "jn1828",
  "sec": "The final week",
  "dt": "Wed 5 Apr AD 30, early",
  "ttl": "“That they might eat the passover”"
  },
  {
  "id": "cross",
  "sec": "The final week",
  "dt": "Wed 5 Apr AD 30 (fixed calendar)",
  "ttl": "The cross: “the preparation of the passover, and about the sixth hour”"
  },
  {
  "id": "jn1942",
  "sec": "The final week",
  "dt": "Wed 5 Apr AD 30, before sunset",
  "ttl": "Burial: “because of the Jews’ preparation day”"
  },
  {
  "id": "high",
  "sec": "The final week",
  "dt": "Thu 6 Apr AD 30",
  "ttl": "“That sabbath day was an high day”"
  },
  {
  "id": "three",
  "sec": "The final week",
  "dt": "Sat 8 Apr AD 30, at sunset",
  "ttl": "Three days and three nights, evening to evening"
  },
  {
  "id": "jn201",
  "sec": "The final week",
  "dt": "Sun 9 Apr AD 30, before dawn",
  "ttl": "“The first day of the week … when it was yet dark”"
  },
  {
  "id": "jn2019",
  "sec": "The final week",
  "dt": "Sun 9 Apr AD 30, evening",
  "ttl": "“The same day at evening … Peace be unto you”"
  },
  {
  "id": "jn2026",
  "sec": "Forty days, and Pentecost · Apr – May AD 30",
  "dt": "Sun 16 Apr AD 30",
  "ttl": "“After eight days”: Thomas"
  },
  {
  "id": "asc",
  "sec": "Forty days, and Pentecost · Apr – May AD 30",
  "dt": "Thu 18 May AD 30",
  "ttl": "Ascension: “being seen of them forty days”"
  },
  {
  "id": "pent",
  "sec": "Forty days, and Pentecost · Apr – May AD 30",
  "dt": "Fri 26 May AD 30 (fixed calendar)",
  "ttl": "“When the day of Pentecost was fully come”"
  }
  ];
  /*MARKERS-END*/
  L.MARKERS = MARKERS;
  L.marker = function (id) { for (var i = 0; i < MARKERS.length; i++) if (MARKERS[i].id === id) return MARKERS[i]; return null; };
  L.shortDate = function (dt) { return String(dt || "").split(/\s\(|,\s/)[0].trim(); };
  L.markerLabel = function (m) { return m ? m.ttl + (m.dt ? " (" + L.shortDate(m.dt) + ")" : "") : ""; };

  /* ===================== YouTube ===================== */
  var ID_RE = /^[A-Za-z0-9_-]{11}$/;
  var MARKER_RE = /^[A-Za-z0-9_-]{1,80}$/;
  L.validId = function (id) { return typeof id === "string" && ID_RE.test(id); };
  L.validMarker = function (id) { return typeof id === "string" && MARKER_RE.test(id); };
  // Accepts youtu.be/ID, youtube.com/watch?v=ID, /shorts/ID, /embed/ID, /live/ID (www., m., music., -nocookie).
  // Returns { id } or { error: "empty" | "notlink" | "notyoutube" | "playlist" | "noid" }.
  L.parseYouTube = function (input) {
    var s = String(input || "").trim().replace(/^<|>$/g, "");
    if (!s) return { error: "empty" };
    var found = s.match(/https?:\/\/\S+/i); if (found) s = found[0];          // pasted text with a link inside it
    if (!/^[a-z][a-z0-9+.-]*:\/\//i.test(s)) s = "https://" + s;
    var u; try { u = new URL(s); } catch (e) { return { error: "notlink" }; }
    if (!/^https?:$/.test(u.protocol) || !/\./.test(u.hostname)) return { error: "notlink" };
    var host = u.hostname.toLowerCase().replace(/^(www|m|music)\./, ""), seg = u.pathname.split("/").filter(Boolean), id = null;
    if (host === "youtu.be") id = seg[0];
    else if (host === "youtube.com" || host === "youtube-nocookie.com") {
      if (seg[0] === "watch") id = u.searchParams.get("v");
      else if (["shorts", "embed", "live", "v", "e"].indexOf(seg[0]) >= 0) id = seg[1];
      else if (seg[0] === "playlist") return { error: "playlist" };
    } else return { error: "notyoutube" };
    return L.validId(id) ? { id: id } : { error: "noid" };
  };
  L.thumb = function (id) { return L.validId(id) ? "https://i.ytimg.com/vi/" + id + "/hqdefault.jpg" : ""; };
  L.embedUrl = function (id, autoplay) {
    return L.validId(id) ? "https://www.youtube-nocookie.com/embed/" + id + "?playsinline=1&rel=0&modestbranding=1" + (autoplay ? "&autoplay=1" : "") : "";
  };

  /* ===================== Google Drive videos [drive-resources] ===================== */
  // Drive file ids are 25-44 characters today; accept 20-100 of the same characters (never 11, so they can't be
  // mistaken for a YouTube id). The database checks the same pattern (migrations/2026-10-04_drive_resources.sql).
  var DRIVE_RE = /^[A-Za-z0-9_-]{20,100}$/;
  L.validDrive = function (id) { return typeof id === "string" && DRIVE_RE.test(id); };
  L.validKey = function (k) { return L.validId(k) || L.validDrive(k); };
  function toUrl(input) {
    var s = String(input || "").trim().replace(/^<|>$/g, "");
    if (!s) return { error: "empty" };
    var found = s.match(/https?:\/\/\S+/i); if (found) s = found[0];          // pasted text with a link inside it
    if (!/^[a-z][a-z0-9+.-]*:\/\//i.test(s)) s = "https://" + s;
    var u; try { u = new URL(s); } catch (e) { return { error: "notlink" }; }
    if (!/^https?:$/.test(u.protocol) || !/\./.test(u.hostname)) return { error: "notlink" };
    return { u: u };
  }
  function isDriveHost(h) { return /^(drive|docs|drive\.usercontent)\.google\.com$/.test(String(h).toLowerCase().replace(/^www\./, "")); }
  // drive.google.com/file/d/ID/view (also /preview, /edit, no ending, ?usp=sharing, &resourcekey=...),
  // drive.google.com/open?id=ID, drive.google.com/uc?id=ID&export=download, drive.usercontent.google.com/download?id=ID,
  // docs.google.com/file/d/ID, the /u/0/ and /a/<domain>/ forms. Returns { id } or { error: "folder" | "gdoc" | "noid" }.
  L.parseDrive = function (u) {
    var seg = u.pathname.split("/").filter(Boolean), id = null;
    if (seg[0] === "a" && seg.length > 2) seg = seg.slice(2);                // Workspace: /a/<domain>/...
    if (seg[0] === "u" && /^\d+$/.test(seg[1] || "")) seg = seg.slice(2);    // signed into several accounts: /u/1/...
    if (seg.indexOf("folders") >= 0 || seg[0] === "embeddedfolderview") return { error: "folder" };
    if (/^(document|spreadsheets|presentation|forms|drawings)$/.test(seg[0] || "")) return { error: "gdoc" };
    if (seg[0] === "file" && seg[1] === "d") id = seg[2];
    else if (/^(open|uc|download|thumbnail)$/.test(seg[0] || "") && seg.length === 1) id = u.searchParams.get("id");
    return L.validDrive(id) ? { id: id } : { error: "noid" };
  };
  // Any video link the leaders may paste: a Google Drive video, or a YouTube video (kept working).
  // Returns { source: "drive" | "youtube", id } or { error: "empty" | "notlink" | "notvideo" | "playlist" | "folder" | "gdoc" | "noid" }.
  L.parseVideo = function (input) {
    var t = toUrl(input); if (t.error) return t;
    if (isDriveHost(t.u.hostname)) { var d = L.parseDrive(t.u); return d.error ? d : { source: "drive", id: d.id }; }
    var y = L.parseYouTube(t.u.href);
    if (y.error) return { error: y.error === "notyoutube" ? "notvideo" : y.error };
    return { source: "youtube", id: y.id };
  };
  L.driveEmbed = function (id) { return L.validDrive(id) ? "https://drive.google.com/file/d/" + id + "/preview" : ""; };
  L.driveThumb = function (id) { return L.validDrive(id) ? "https://drive.google.com/thumbnail?id=" + id + "&sz=w640" : ""; };
  // A lesson row's video: "drive" | "youtube" | null. Rows from before the Drive columns existed are YouTube rows.
  L.src = function (row) {
    if (!row) return null;
    if (row.video_source === "drive" || (!L.validId(row.youtube_id) && row.drive_id)) return L.validDrive(row.drive_id) ? "drive" : null;
    if (L.validId(row.youtube_id)) return "youtube";
    if (row.drive_id === undefined && row.youtube_url) {                       // database not updated yet: read the link itself
      var v = L.parseVideo(row.youtube_url);
      if (v.source === "drive") { row.drive_id = v.id; row.video_source = "drive"; return "drive"; }
    }
    return null;
  };
  L.vkey = function (row) { var s = L.src(row); return s === "drive" ? row.drive_id : s === "youtube" ? row.youtube_id : null; };
  L.thumbFor = function (row) { var s = L.src(row); return s === "drive" ? L.driveThumb(row.drive_id) : s === "youtube" ? L.thumb(row.youtube_id) : ""; };
  // <img> attributes for a lesson picture. Drive only has a picture once it has processed the video (and only when
  // the file is shared "Anyone with the link"): if it fails, a plain dark tile with the play button is shown instead.
  L.thumbAttrs = function (row) { return ' src="' + esc(L.thumbFor(row)) + '"' + (L.src(row) === "drive" ? ' data-lxfb="1" referrerpolicy="no-referrer"' : ""); };
  document.addEventListener("error", function (e) {
    var t = e.target;
    if (t && t.tagName === "IMG" && t.getAttribute("data-lxfb") === "1" && !t._lxfb) { t._lxfb = 1; t.style.visibility = "hidden"; if (t.parentNode && t.parentNode.classList) t.parentNode.classList.add("lx-nothumb"); }
  }, true);

  /* ===================== Bible references + checked KJV ===================== */
  var BOOKS = ["Genesis","Exodus","Leviticus","Numbers","Deuteronomy","Joshua","Judges","Ruth","1 Samuel","2 Samuel","1 Kings","2 Kings",
    "1 Chronicles","2 Chronicles","Ezra","Nehemiah","Esther","Job","Psalms","Proverbs","Ecclesiastes","Song of Solomon","Isaiah","Jeremiah",
    "Lamentations","Ezekiel","Daniel","Hosea","Joel","Amos","Obadiah","Jonah","Micah","Nahum","Habakkuk","Zephaniah","Haggai","Zechariah",
    "Malachi","Matthew","Mark","Luke","John","Acts","Romans","1 Corinthians","2 Corinthians","Galatians","Ephesians","Philippians",
    "Colossians","1 Thessalonians","2 Thessalonians","1 Timothy","2 Timothy","Titus","Philemon","Hebrews","James","1 Peter","2 Peter",
    "1 John","2 John","3 John","Jude","Revelation"];
  var CHAPTERS = [50,40,27,36,34,24,21,4,31,24,22,25,29,36,10,13,10,42,150,31,12,8,66,52,5,48,12,14,3,9,1,4,7,3,3,3,2,14,4,28,16,24,21,28,16,16,13,6,6,4,4,5,3,6,4,3,1,13,5,5,3,5,1,1,1,22];
  var ABBR = {
    "gen":0,"ge":0,"gn":0,"exod":1,"exo":1,"ex":1,"lev":2,"le":2,"lv":2,"num":3,"nu":3,"nm":3,"nb":3,"deut":4,"deu":4,"de":4,"dt":4,
    "josh":5,"jos":5,"jsh":5,"judg":6,"jdg":6,"jg":6,"jdgs":6,"rth":7,"ru":7,"1 sam":8,"1 sa":8,"1 sm":8,"2 sam":9,"2 sa":9,"2 sm":9,
    "1 kgs":10,"1 ki":10,"1 kin":10,"2 kgs":11,"2 ki":11,"2 kin":11,"1 chr":12,"1 chron":12,"1 ch":12,"2 chr":13,"2 chron":13,"2 ch":13,
    "ezr":14,"neh":15,"ne":15,"esth":16,"est":16,"es":16,"jb":17,"psalm":18,"ps":18,"psa":18,"pss":18,"psm":18,"prov":19,"pro":19,"prv":19,"pr":19,
    "eccl":20,"ecc":20,"eccles":20,"ec":20,"qoh":20,"song":21,"song of songs":21,"sos":21,"canticles":21,"cant":21,"song of sol":21,
    "isa":22,"is":22,"jer":23,"je":23,"jr":23,"lam":24,"la":24,"ezek":25,"eze":25,"ezk":25,"dan":26,"da":26,"dn":26,"hos":27,"ho":27,
    "jl":28,"am":29,"obad":30,"ob":30,"jon":31,"jnh":31,"mic":32,"mc":32,"nah":33,"na":33,"hab":34,"hb":34,"zeph":35,"zep":35,"zp":35,
    "hag":36,"hg":36,"zech":37,"zec":37,"zc":37,"mal":38,"ml":38,"matt":39,"mat":39,"mt":39,"mrk":40,"mk":40,"mr":40,"luk":41,"lk":41,
    "jn":42,"jhn":42,"joh":42,"act":43,"ac":43,"rom":44,"ro":44,"rm":44,"1 cor":45,"1 co":45,"2 cor":46,"2 co":46,"gal":47,"ga":47,
    "eph":48,"ephes":48,"phil":49,"php":49,"pp":49,"col":50,"1 thess":51,"1 thes":51,"1 th":51,"2 thess":52,"2 thes":52,"2 th":52,
    "1 tim":53,"1 ti":53,"2 tim":54,"2 ti":54,"tit":55,"philem":56,"phm":56,"phlm":56,"heb":57,"jas":58,"jm":58,
    "1 pet":59,"1 pe":59,"1 pt":59,"2 pet":60,"2 pe":60,"2 pt":60,"1 jn":61,"1 jhn":61,"1 jo":61,"1 joh":61,"2 jn":62,"2 jhn":62,"2 jo":62,
    "3 jn":63,"3 jhn":63,"3 jo":63,"jud":64,"jde":64,"rev":65,"re":65,"revelations":65,"the revelation":65,"revelation of john":65
  };
  BOOKS.forEach(function (b, i) { ABBR[b.toLowerCase()] = i; });
  function bookKey(s) {
    return String(s || "").toLowerCase().replace(/\./g, " ").replace(/^\s*(first|1st|i)\s+/, "1 ").replace(/^\s*(second|2nd|ii)\s+/, "2 ")
      .replace(/^\s*(third|3rd|iii)\s+/, "3 ").replace(/^([123])\s*(?=[a-z])/, "$1 ").replace(/\s+/g, " ").trim();
  }
  L.findBook = function (name) { var k = bookKey(name); return k in ABBR ? ABBR[k] : -1; };
  L.BOOKS = BOOKS;
  var MAX_REF_VERSES = 40, MAX_LESSON_VERSES = 80;

  // "John 7:37-38; Leviticus 23:34, 36; Ps 23" -> [{ raw, ok, b, c1, v1, c2, v2, whole, label } | { raw, ok:false, why }]
  L.parseRefs = function (text) {
    var out = [], book = -1, chap = 0;
    String(text || "").replace(/[\u2013\u2014\u2012]/g, "-").replace(/\s+to\s+/gi, "-").split(/[;\n]+/).forEach(function (part) {
      part.split(",").forEach(function (tok) {
        var raw = tok.trim().replace(/\s*\(?kjv\)?\.?$/i, "").replace(/[.\s]+$/, "");
        if (!raw) return;
        var m = raw.match(/^((?:[1-3]|i{1,3}|1st|2nd|3rd|first|second|third)?\s*[a-z][a-z .']*?)\s*(\d[\d:.\-\sabc]*)?$/i), nums, newBook = false;
        if (m && /[a-z]{2,}/i.test(m[1])) {
          var b = L.findBook(m[1]);
          if (b < 0) { out.push({ raw: raw, ok: false, why: "book" }); book = -1; return; }
          book = b; chap = 0; newBook = true; nums = m[2] || "";
        } else if (/^\d/.test(raw)) {
          if (book < 0) { out.push({ raw: raw, ok: false, why: "nobook" }); return; }
          nums = raw;
        } else { out.push({ raw: raw, ok: false, why: "format" }); return; }
        nums = nums.replace(/\s+/g, "").replace(/(\d)[a-c](?=$|-)/g, "$1").replace(/^(\d+)\.(\d+)/, "$1:$2");
        var r = { raw: raw, ok: true, b: book }, x;
        if (!nums) { out.push({ raw: raw, ok: false, why: "nochapter" }); return; }
        if ((x = nums.match(/^(\d+):(\d+)(?:-(\d+)(?::(\d+))?)?$/))) {
          r.c1 = +x[1]; r.v1 = +x[2];
          if (x[4]) { r.c2 = +x[3]; r.v2 = +x[4]; } else { r.c2 = r.c1; r.v2 = x[3] ? +x[3] : r.v1; }
          chap = r.c2;
        } else if ((x = nums.match(/^(\d+)(?:-(\d+))?$/))) {
          var a = +x[1], z = x[2] ? +x[2] : a;
          if (CHAPTERS[book] === 1) { r.c1 = r.c2 = 1; r.v1 = a; r.v2 = z; chap = 1; }            // Jude 3, Philemon 1:10-ish
          else if (!newBook && chap) { r.c1 = r.c2 = chap; r.v1 = a; r.v2 = z; }                // "John 7:37, 39"
          else { r.c1 = a; r.c2 = z; r.v1 = 1; r.v2 = 0; r.whole = true; chap = 0; }            // whole chapter(s)
        } else { out.push({ raw: raw, ok: false, why: "format" }); return; }
        if (r.c1 < 1 || r.c2 > CHAPTERS[book] || r.c1 > CHAPTERS[book]) { out.push({ raw: raw, ok: false, why: "chapter" }); return; }
        if (r.c2 < r.c1 || (r.c2 === r.c1 && !r.whole && r.v2 < r.v1) || r.v1 < 1) { out.push({ raw: raw, ok: false, why: "order" }); return; }
        r.label = BOOKS[book] + " " + r.c1 + (r.whole ? (r.c2 !== r.c1 ? "\u2013" + r.c2 : "") :
          ":" + r.v1 + (r.c2 !== r.c1 ? "\u2013" + r.c2 + ":" + r.v2 : r.v2 !== r.v1 ? "\u2013" + r.v2 : ""));
        out.push(r);
      });
    });
    return out;
  };

  L.kjvBase = "kjv/";
  var bookCache = {};
  L.loadBook = function (b) {
    if (!bookCache[b]) {
      var n = (b + 1 < 10 ? "0" : "") + (b + 1);
      bookCache[b] = fetch(L.kjvBase + n + ".json", { credentials: "omit" }).then(function (r) {
        if (!r.ok) throw new Error("HTTP " + r.status); return r.json();
      }).then(function (d) {
        if (!d || d.length !== CHAPTERS[b]) throw new Error("bad KJV file"); return d;
      }).catch(function (e) { delete bookCache[b]; throw e; });
    }
    return bookCache[b];
  };
  // -> Promise<[{ raw, ok, label, verses:[{c,v,t}] } | { raw, ok:false, why, label? }]> (never rejects)
  L.resolveRefs = function (text) {
    var items = L.parseRefs(text), total = 0;
    return Promise.all(items.map(function (r) {
      if (!r.ok) return Promise.resolve(r);
      return L.loadBook(r.b).then(function (bk) {
        var vs = [], c, v, ch, last, bad = "";
        for (c = r.c1; c <= r.c2 && !bad; c++) {
          ch = bk[c - 1]; if (!ch) { bad = "chapter"; break; }
          var from = c === r.c1 ? r.v1 : 1, to = r.whole || c !== r.c2 ? ch.length : r.v2;
          if (from > ch.length || to > ch.length) { bad = "verse"; break; }
          for (v = from; v <= to; v++) {
            if (typeof ch[v - 1] !== "string") { bad = "unverified"; break; }
            vs.push({ c: c, v: v, t: ch[v - 1] });
            if (vs.length > MAX_REF_VERSES) { bad = "long"; break; }
          }
        }
        if (!bad && total + vs.length > MAX_LESSON_VERSES) bad = "long";
        if (bad) return { raw: r.raw, ok: false, why: bad, label: r.label, n: vs.length };
        total += vs.length;
        return { raw: r.raw, ok: true, label: r.label, verses: vs };
      }, function () { return { raw: r.raw, ok: false, why: "offline", label: r.label }; });
    }));
  };
  L.refProblem = function (r) {
    return ({ book: "we don’t recognise that book name", nobook: "it needs a book name first (e.g. John 7:37)",
      format: "we couldn’t read that reference (try the form John 7:37-38)", nochapter: "it needs a chapter and verse",
      chapter: "that book doesn’t have that chapter", verse: "that chapter doesn’t have that verse", order: "the verse numbers are back to front",
      long: "that passage is too long to show in full (up to " + MAX_REF_VERSES + " verses per reference)",
      unverified: "this verse’s wording couldn’t be double-checked in our KJV sources", offline: "the KJV text couldn’t be loaded just now" })[r.why] || "it couldn’t be checked";
  };
  // HTML for one resolved reference. Verse text is KJV from kjv/*.json (escaped anyway).
  L.verseHTML = function (r) {
    if (!r.ok) return '<div class="ln lx-refonly"><span class="ref">' + esc(r.label || r.raw) + "</span></div>";
    var multi = r.verses.length > 1, q = r.verses.map(function (x, i) {
      return (multi ? '<sup class="lx-vn">' + (x.v === 1 && i ? x.c + ":" : "") + x.v + "</sup>" : "") + esc(x.t);
    }).join(" ");
    return '<div class="ln lT" data-t="T"><span class="tag kT">TEXT</span><span class="ref">' + esc(r.label) + '</span> <span class="q">“' + q + "”</span></div>";
  };

  /* ===================== summary text (plain text -> safe paragraphs) ===================== */
  L.summaryHTML = function (s) {
    s = String(s || "").replace(/\r\n?/g, "\n").trim(); if (!s) return "";
    return s.split(/\n\s*\n/).map(function (p) { return "<p>" + esc(p.trim()).replace(/\n/g, "<br>") + "</p>"; }).join("");
  };
  L.isNew = function (row) { var t = Date.parse(row && row.created_at); return !!t && Date.now() - t < 7 * 86400e3 && Date.now() - t > -86400e3; };
  L.dateLabel = function (ts) { var d = new Date(ts); return isNaN(d) ? "" : d.toLocaleDateString(undefined, { month: "short", day: "numeric" }); };

  /* ===================== data ===================== */
  var COLS_OLD = "id,created_at,updated_at,created_by,title,youtube_url,youtube_id,marker_id,summary,verse_refs,sort_order,published,notified";
  // [drive-resources] "*" = the columns above + video_source, drive_id once the Drive migration has run (every column of
  // public.lessons is fine for members to read). Before that migration the same request still works (no new columns:
  // YouTube lessons keep working, and saving a Drive link explains what's needed). The old list stays as a fallback.
  var COLS = "*";
  L.isMissingColumn = function (err) {
    var m = String((err && (err.message || err.details || err.hint)) || "") + " " + String(err && err.code || "");
    return /PGRST204|42703/.test(m) || /column .*(video_source|drive_id)|(video_source|drive_id).* column/i.test(m);
  };
  var DEMO_KEY = "ad30m.demoLessons", CACHE_KEY = "ad30m.lessons";
  function lsGet(k, d) { return AD30.LS ? AD30.LS.get(k, d) : d; }
  function lsSet(k, v) { if (AD30.LS) AD30.LS.set(k, v); }
  L.isMissingTable = function (err) {
    if (L.isMissingColumn(err)) return false;
    var m = String((err && (err.message || err.details || err.hint)) || "") + " " + String(err && err.code || "");
    return /PGRST205|42P01|schema cache|does not exist|relation .*lessons/i.test(m);
  };
  // PostgREST answers 404 for a table it doesn't know (the migration hasn't been run yet)
  var MISSING = { code: "PGRST205", message: "The lessons table doesn't exist yet (HTTP 404)" };
  function timeout(p, ms) {
    return new Promise(function (res, rej) { var t = setTimeout(function () { rej(new Error("timeout")); }, ms); p.then(function (v) { clearTimeout(t); res(v); }, function (e) { clearTimeout(t); rej(e); }); });
  }
  L.timeout = timeout;
  // opts.all = admin list (published + hidden). Members always get published only, newest first.
  // Resolves { rows, error, missing, fromCache } - never rejects.
  L.fetch = function (opts) {
    opts = opts || {};
    if (AD30.demo) return Promise.resolve({ rows: lsGet(DEMO_KEY, []).filter(function (r) { return opts.all || r.published; }) });
    if (!AD30.sb) return Promise.resolve({ rows: [], error: "not connected" });
    function query() {
      var q = AD30.sb.from("lessons").select(COLS);
      if (!opts.all) q = q.eq("published", true);
      return timeout(q.order("created_at", { ascending: false }).limit(300), opts.ms || 9000);
    }
    return query().then(function (r) {
      if (r.error && COLS !== COLS_OLD && L.isMissingColumn(r.error)) { COLS = COLS_OLD; L.driveReady = false; return query(); }
      return r;
    }).then(function (r) {
      if (r.error) throw r.status === 404 ? MISSING : r.error;
      var rows = (r.data || []).filter(function (x) { return x && (opts.all || x.published !== false); });
      if (!opts.all) lsSet(CACHE_KEY, { rows: rows, at: Date.now() });
      return { rows: rows };
    }).catch(function (e) {
      var missing = L.isMissingTable(e);
      if (!opts.all && !missing) { var c = lsGet(CACHE_KEY, null); if (c && c.rows) return { rows: c.rows, error: String(e.message || e), fromCache: true }; }
      if (missing && AD30.LS) AD30.LS.del(CACHE_KEY);
      return { rows: [], error: String((e && e.message) || e), missing: missing };
    });
  };
  // admin writes (RLS: admins only)
  L.save = function (row, id) {
    if (AD30.demo) {
      var list = lsGet(DEMO_KEY, []), now = new Date().toISOString(), hit = null;
      list.forEach(function (x) { if (x.id === id) hit = x; });
      if (hit) { Object.keys(row).forEach(function (k) { hit[k] = row[k]; }); hit.updated_at = now; }
      else { hit = Object.assign({ id: "demo-" + Date.now(), created_at: now, updated_at: now, created_by: "demo@example.com", published: true, notified: false }, row); list.unshift(hit); }
      lsSet(DEMO_KEY, list); return Promise.resolve({ data: hit });
    }
    var q = id ? AD30.sb.from("lessons").update(row).eq("id", id).select(COLS) : AD30.sb.from("lessons").insert(row).select(COLS);
    return timeout(q, 15000).then(function (r) {
      if (r.error) return { error: r.status === 404 ? MISSING : r.error };
      if (!r.data || !r.data.length) return { error: { message: "AD30_NOT_SAVED" } };
      return { data: r.data[0] };
    }, function (e) { return { error: e }; });
  };
  L.remove = function (id) {
    if (AD30.demo) { lsSet(DEMO_KEY, lsGet(DEMO_KEY, []).filter(function (x) { return x.id !== id; })); return Promise.resolve({}); }
    return timeout(AD30.sb.from("lessons").delete().eq("id", id).select("id"), 15000).then(function (r) {
      if (r.error) return { error: r.status === 404 ? MISSING : r.error };
      if (!r.data || !r.data.length) return { error: { message: "AD30_NOT_SAVED" } };
      return {};
    }, function (e) { return { error: e }; });
  };
  L.usable = function (rows) {
    var seen = {};
    return (rows || []).filter(function (r) {
      var k = L.vkey(r);
      if (!k || !String(r.title || "").trim() || seen[k]) return false;
      seen[k] = 1; return true;
    });
  };
  function byOrder(a, b) {
    var x = a.sort_order == null ? 1e9 : a.sort_order, y = b.sort_order == null ? 1e9 : b.sort_order;
    return x - y || String(a.created_at).localeCompare(String(b.created_at));
  }

  /* ===================== verses filled in when they come into view ===================== */
  var io = null;
  function fillVerses(el) {
    if (el._lxDone) return; el._lxDone = true;
    L.resolveRefs(el.getAttribute("data-refs")).then(function (list) {
      el.innerHTML = list.map(L.verseHTML).join("");
      el.classList.add("lx-filled");
      if (L._apply) try { L._apply(); } catch (e) {}      // timeline: respect the TEXT filter chip
    });
  }
  L.watchVerses = function (root) {
    var els = (root || document).querySelectorAll(".lx-verses[data-refs]");
    if (!("IntersectionObserver" in window)) { [].forEach.call(els, fillVerses); return; }
    if (!io) io = new IntersectionObserver(function (ents) {
      ents.forEach(function (e) { if (e.isIntersecting || e.intersectionRatio > 0) { io.unobserve(e.target); fillVerses(e.target); } });
    }, { rootMargin: "300px 0px" });
    [].forEach.call(els, function (el) { if (!el._lxDone) io.observe(el); });
  };
  function versesPlaceholder(refs) {
    return refs ? '<div class="lx-verses" data-refs="' + esc(refs) + '"><div class="ln lx-refonly"><span class="ref">' + esc(refs) + "</span></div></div>" : "";
  }
  function summaryBlock(row, simple) {
    var s = L.summaryHTML(row.summary); if (!s) return "";
    return simple ? '<p class="lx-k">Lesson summary</p><div class="lx-text">' + s + "</div>"
                  : '<div class="ln lx-sum"><span class="tag kL">LESSON SUMMARY</span><div class="lx-text">' + s + "</div></div>";
  }

  /* ===================== full timeline (index.html) ===================== */
  // tl = helpers from timeline.js (setOpen, openTarget, mountYT, badge, apply, paintWatched, optional after)
  L.timeline = function (tl) {
    return L.fetch().then(function (res) {
      try { renderTimeline(tl || {}, L.usable(res.rows)); } catch (e) { if (window.console) console.warn("[lessons]", e); }
      // [drive-resources] PDFs, pictures and links from the leaders (js/resources.js), placed after the lessons
      if (window.AD30R && window.AD30R.timeline) try { window.AD30R.timeline(tl || {}); } catch (e) { if (window.console) console.warn("[resources]", e); }
      return res;
    });
  };
  function lessonFigure(row) {
    var id = L.vkey(row), drive = L.src(row) === "drive", fig = document.createElement("figure");
    fig.className = "vid sheetvid lx-fig" + (drive ? " lx-dfig" : ""); fig.id = "sv-" + id;
    fig.setAttribute("data-key", id); fig.setAttribute(drive ? "data-drive" : "data-yt", id); fig.setAttribute("data-title", String(row.title).slice(0, 200));
    fig.innerHTML = '<figcaption><span class="hasv">▶ WATCH</span><span class="tag kL">VIDEO LESSON</span>' + (L.isNew(row) ? '<span class="lx-new">NEW</span> ' : "") +
      esc(row.title) + "</figcaption>" +
      (drive ? '<div class="ytbox lx-dbox"><button type="button" class="lx-thumb lx-dposter" aria-label="Play video: ' + esc(row.title) + '"><img alt="" loading="lazy" decoding="async"' + L.thumbAttrs(row) + '><span class="lx-play" aria-hidden="true"></span></button></div>'
             : '<div class="ytbox"><div></div></div>') + summaryBlock(row) + versesPlaceholder(row.verse_refs);
    if (drive) fig.querySelector(".lx-dposter").addEventListener("click", function () { L.player(fig.querySelector(".lx-dbox"), row); });
    return fig;
  }
  function renderTimeline(tl, rows) {
    var top = document.getElementById("lxTop"); if (!top || !rows.length) return;
    var gen = document.getElementById("lxGeneral"), placed = [];
    rows.slice().sort(byOrder).forEach(function (row) {
      var id = L.vkey(row);
      if (document.getElementById("sv-" + id) || document.querySelector('.vid[data-key="' + id + '"]')) return;   // already on the page
      var li = L.validMarker(row.marker_id) ? document.getElementById(row.marker_id) : null, fig = lessonFigure(row);
      if (!li || !li.classList.contains("ev") || li.classList.contains("sv") || li.classList.contains("lx-gen")) {
        li = document.createElement("li");
        li.className = "ev sv lx-gen"; li.id = "lx-" + id; li.setAttribute("data-place", "V"); li.setAttribute("data-tags", "V");
        li.innerHTML = '<span class="dot kL"></span><button class="hd" aria-expanded="false" aria-controls="b-lx-' + id + '">' +
          '<span class="dt">' + (L.isNew(row) ? '<span class="lx-new">NEW</span> ' : "") + "Video lesson · added " + esc(L.dateLabel(row.created_at)) + "</span>" +
          '<span class="ttl">' + esc(row.title) + '</span><span class="meta"><span class="pv">' + esc(row.verse_refs || "") + '</span><span class="chev">▾</span></span></button>' +
          '<div class="body" id="b-lx-' + id + '" hidden></div>';
        gen.appendChild(li); li.querySelector(".body").appendChild(fig); row._where = "General";
      } else {
        var body = li.querySelector(".body"), figs = body.querySelectorAll("figure.vid");
        if (figs.length) figs[figs.length - 1].insertAdjacentElement("afterend", fig); else body.insertBefore(fig, body.firstChild);
        var t = li.querySelector(".ttl"), d = li.querySelector(".dt");
        row._where = (t ? t.textContent : "") + (d ? " · " + L.shortDate(d.textContent) : "");
      }
      if (tl.badge) tl.badge(li);
      if (li.classList.contains("open") && tl.mountYT) tl.mountYT(li);
      placed.push(row);
    });
    if (!placed.length) return;
    // "Latest lessons" strip: newest first
    var strip = document.getElementById("lxStrip");
    placed.slice().sort(function (a, b) { return String(b.created_at).localeCompare(String(a.created_at)); }).slice(0, 12).forEach(function (row) {
      var a = document.createElement("a");
      var key = L.vkey(row);
      a.className = "lx-card"; a.href = "#v-" + key; a.setAttribute("data-lx", key); a.setAttribute("role", "listitem");
      a.innerHTML = '<span class="lx-thumb"><img alt="" loading="lazy" decoding="async"' + L.thumbAttrs(row) + '><span class="lx-play" aria-hidden="true"></span>' +
        (L.isNew(row) ? '<span class="lx-new">NEW</span>' : "") + '</span><span class="lx-ct">' + esc(row.title) + '</span><span class="lx-cw">' + esc(row._where) + "</span>";
      a.addEventListener("click", function (ev) {
        ev.preventDefault();
        if (tl.openTarget) tl.openTarget("v-" + key);
        if (AD30.track) AD30.track("card_open", { marker_id: "lesson-strip", video_id: key, video_title: String(row.title).slice(0, 200) });
      });
      strip.appendChild(a);
    });
    top.hidden = false;
    var lg = document.querySelector(".legend p:nth-child(2)");
    if (lg && !lg.querySelector(".kL")) lg.insertAdjacentHTML("beforeend", ' · <span class="tag kL">LESSON SUMMARY</span> the group leader’s summary of a video lesson (teaching, not Scripture)');
    L._apply = tl.apply;
    if (tl.apply) tl.apply();
    if (tl.paintWatched) tl.paintWatched();
    L.watchVerses(document);
    if (tl.after) try { tl.after(); } catch (e) {}      // v2: let the progress / "what's new" features count lesson videos
  }

  /* ===================== YouTube player (simple view) ===================== */
  var ytReady = null;
  function loadYT() {
    if (window.YT && window.YT.Player) return Promise.resolve(window.YT);
    if (ytReady) return ytReady;
    ytReady = new Promise(function (resolve, reject) {
      var prev = window.onYouTubeIframeAPIReady;
      window.onYouTubeIframeAPIReady = function () { if (prev) try { prev(); } catch (e) {} resolve(window.YT); };
      if (!document.querySelector('script[src*="youtube.com/iframe_api"]')) {
        var s = document.createElement("script"); s.src = "https://www.youtube.com/iframe_api"; s.async = true;
        s.onerror = function () { ytReady = null; reject(new Error("YouTube blocked")); };
        document.head.appendChild(s);
      }
      var poll = setInterval(function () { if (window.YT && window.YT.Player) { clearInterval(poll); resolve(window.YT); } }, 250);
      setTimeout(function () { clearInterval(poll); if (!(window.YT && window.YT.Player)) { ytReady = null; reject(new Error("YouTube timeout")); } }, 10000);
    });
    return ytReady;
  }
  var sentMs = {};
  function track(kind, row, extra) {
    if (!AD30.track) return;
    var f = { marker_id: row.marker_id || "lessons", video_id: L.vkey(row), video_title: String(row.title).slice(0, 200) };
    if (extra) Object.keys(extra).forEach(function (k) { f[k] = extra[k]; });
    AD30.track(kind, f);
  }
  var players = [];
  function pauseOthers(me) {
    players.forEach(function (p) { if (p !== me && p.pauseVideo) try { p.pauseVideo(); } catch (e) {} });
    if (me) L.stopDrive(document);
    [].forEach.call(document.querySelectorAll("video"), function (v) { try { v.pause(); } catch (e) {} });
  }
  // Puts a player into holder (replacing its content). Tracks play / 25 / 50 / 75 / complete like the other videos.
  L.player = function (holder, row) {
    if (L.src(row) === "drive") return drivePlayer(holder, row);
    var id = row.youtube_id; if (!L.validId(id)) return;
    var s = sentMs[id] || (sentMs[id] = { m: {}, done: false, played: false });
    holder.innerHTML = '<div class="lx-yt"><div></div></div>';
    var inner = holder.firstChild.firstChild, poll = null;
    function prog(p) {
      try {
        var cur = p.getCurrentTime(), dur = p.getDuration(); if (!dur) return;
        [25, 50, 75].forEach(function (m) { if (cur / dur * 100 >= m && !s.m[m]) { s.m[m] = 1; track("video_progress", row, { progress_pct: m }); } });
        if (cur / dur >= 0.9 && !s.done) { s.done = true; track("video_complete", row, { progress_pct: 100 }); }
      } catch (e) {}
    }
    loadYT().then(function (YT) {
      if (!inner.isConnected) return;
      var p = new YT.Player(inner, {
        videoId: id, host: "https://www.youtube-nocookie.com", width: "100%", height: "100%",
        playerVars: { playsinline: 1, rel: 0, modestbranding: 1, origin: location.origin },
        events: {
          onReady: function (e) { try { e.target.playVideo(); } catch (x) {} },
          onStateChange: function (e) {
            if (e.data === 1) { if (!s.played) { s.played = true; track("video_play", row); } pauseOthers(p); clearInterval(poll); poll = setInterval(function () { prog(p); }, 2000); }
            else if (e.data === 2) { clearInterval(poll); prog(p); }
            else if (e.data === 0) { clearInterval(poll); if (!s.done) { s.done = true; track("video_complete", row, { progress_pct: 100 }); } }
          }
        }
      });
      players.push(p); holder._lxPlayer = p;
    }).catch(function () {
      var f = document.createElement("iframe");
      f.src = L.embedUrl(id, true); f.title = String(row.title);
      f.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen";
      f.setAttribute("allowfullscreen", ""); holder.firstChild.innerHTML = ""; holder.firstChild.appendChild(f);
    });
  };

  /* ===================== Google Drive player [drive-resources] ===================== */
  // Drive's own player in an iframe (https://drive.google.com/file/d/<ID>/preview), 16:9, full screen allowed. It
  // replaces the picture when tapped (so a page with many lessons doesn't load many players). Drive doesn't tell the
  // page about play / progress, so only the tap is counted (as video_play).
  function drivePlayer(holder, row) {
    var id = row.drive_id; if (!L.validDrive(id) || !holder) return;
    L.stopDrive(document);
    pauseOthers(null);
    if (!holder._lxKeep) holder._lxKeep = [].slice.call(holder.childNodes);
    holder.innerHTML = "";
    var box = document.createElement("div"), f = document.createElement("iframe");
    box.className = "lx-yt lx-drive";
    f.src = L.driveEmbed(id); f.title = String(row.title || "Video");
    f.allow = "autoplay; fullscreen; encrypted-media; picture-in-picture";
    f.setAttribute("allowfullscreen", ""); f.setAttribute("data-lxdrive", id);
    box.appendChild(f); holder.appendChild(box);
    var s = sentMs[id] || (sentMs[id] = { m: {}, done: false, played: false });
    if (!s.played) { s.played = true; track("video_play", row, { source: "drive" }); }
  }
  // Put the picture back (stops a Drive video that is playing) - used when a section/marker closes or another video starts.
  L.stopDrive = function (root, except) {
    [].forEach.call((root || document).querySelectorAll("iframe[data-lxdrive]"), function (f) {
      if (f === except) return;
      var box = f.parentNode, h = box && box.parentNode;
      if (h && h._lxKeep) { h.innerHTML = ""; h._lxKeep.forEach(function (n) { h.appendChild(n); }); h._lxKeep = null; }
      else if (box) box.parentNode && box.parentNode.removeChild(box);
    });
  };

  /* ===================== simple view (simple.html): big lesson cards ===================== */
  L.simple = function () {
    return L.fetch().then(function (res) {
      try { renderSimple(L.usable(res.rows)); } catch (e) { if (window.console) console.warn("[lessons]", e); }
      return res;
    });
  };
  function renderSimple(rows) {
    var sec = document.getElementById("lxSimple"), list = document.getElementById("lxList"); if (!sec || !list || !rows.length) return;
    list.innerHTML = "";
    rows.forEach(function (row) {      // newest first
      var id = L.vkey(row), m = L.validMarker(row.marker_id) ? L.marker(row.marker_id) : null;
      var li = document.createElement("li"); li.className = "lx-sc"; li.id = "lxs-" + id;
      var more = summaryBlock(row, true) + (row.verse_refs ? '<p class="lx-k">What Scripture says (KJV, exact)</p>' + versesPlaceholder(row.verse_refs) : "");
      li.innerHTML = '<div class="lx-media"><button type="button" class="lx-thumb" aria-label="Play video: ' + esc(row.title) + '">' +
        '<img alt="" loading="lazy" decoding="async"' + L.thumbAttrs(row) + '><span class="lx-play" aria-hidden="true"></span></button></div>' +
        '<h3 class="lx-sc-t serif">' + esc(row.title) + (L.isNew(row) ? ' <span class="lx-new">NEW</span>' : "") + "</h3>" +
        '<p class="lx-sc-d">Added ' + esc(L.dateLabel(row.created_at)) + (m ? " · On the timeline: " + esc(L.markerLabel(m)) : "") + "</p>" +
        (more ? '<button type="button" class="lx-more-btn" aria-expanded="false" aria-controls="lxs-m-' + id + '">Show the summary and verses</button>' +
          '<div class="lx-more" id="lxs-m-' + id + '" hidden>' + more + "</div>" : "") +
        '<p class="lx-sc-l"><a href="./#v-' + id + '">See it on the full timeline →</a></p>';
      li.querySelector(".lx-thumb").addEventListener("click", function () {
        L.player(li.querySelector(".lx-media"), row);
        if (AD30.track) AD30.track("card_open", { marker_id: row.marker_id || "lessons", video_id: id });
      });
      var mb = li.querySelector(".lx-more-btn");
      if (mb) mb.addEventListener("click", function () {
        var box = li.querySelector(".lx-more"), open = box.hidden;
        box.hidden = !open; mb.setAttribute("aria-expanded", open ? "true" : "false");
        mb.textContent = open ? "Hide the summary and verses" : "Show the summary and verses";
        if (open) L.watchVerses(box);
      });
      list.appendChild(li);
    });
    sec.hidden = false;
  }
  // simple view deep link (#v-<id> from a future email): scroll to the lesson card
  L.openSimple = function (want) {
    var id = String(want || "").replace(/^v-/, ""); if (!L.validKey(id)) return false;
    var li = document.getElementById("lxs-" + id); if (!li) return false;
    setTimeout(function () { li.scrollIntoView({ block: "start", behavior: "smooth" }); li.classList.add("lx-flash"); }, 60);
    return true;
  };
})();
