// GENERATED by simple-rework-tools/build_simple_data.py - do not edit by hand.
// Member (simple) view content, built only from text already on the site (index.html timeline + the six simple cards).
// Scripture = exact KJV (checked against js/kjv-verses.js and two full KJV texts). Teaching = the guide's and the
// video lesson's own lines. Teacher-only notes (our computations, disagreements and placements) are NOT included.
// descriptionDerived: true = short description written from the site text for that section; awaiting Ben's approval.
window.AD30_SIMPLE = {
 "generated": "2026-10-04 18:57 ET",
 "kjvNote": "Scripture quotations are from the King James Version (KJV).",
 "sections": [
  {
   "id": "birth",
   "kind": "lesson",
   "title": "Birth",
   "date": "Sept 11, 5 BC",
   "dateNote": "Professor Zac’s guide",
   "aliases": [
    "birth",
    "nativity",
    "trumpets"
   ],
   "timelineIds": [
    "birth"
   ],
   "description": "Professor Zac’s guide places the birth on the Day of Atonement, 10 Tishri — 11 September 5 BC. The guide says plainly that no text gives the day of the birth: it is placed there “because of what the day means,” and that is named as belief, not as evidence.",
   "descriptionDerived": true,
   "video": null,
   "verses": [
    {
     "ref": "Luke 2:11",
     "text": "For unto you is born this day in the city of David a Saviour, which is Christ the Lord."
    },
    {
     "ref": "Leviticus 23:27",
     "text": "Also on the tenth day of this seventh month there shall be a day of atonement: it shall be an holy convocation unto you; and ye shall afflict your souls, and offer an offering made by fire unto the LORD."
    }
   ],
   "teaching": [
    {
     "from": "guide",
     "marker": "birth",
     "html": "Guide’s chart: <b>10 Tishri AM 3757 = 11 September 5 BC</b>, “the Day of Atonement.”"
    },
    {
     "from": "guide",
     "marker": "birth",
     "html": "“The tenth of Tishri is a conviction. No text gives the day of the birth. It is placed on the Day of Atonement because of what the day means, and that is named as belief, not as evidence.”"
    }
   ]
  },
  {
   "id": "jordan",
   "kind": "lesson",
   "title": "The Jordan",
   "date": "Sept 11, AD 26",
   "dateNote": "Professor Zac’s guide",
   "aliases": [
    "jordan",
    "baptism",
    "the jordan"
   ],
   "timelineIds": [
    "jordan"
   ],
   "description": "The guide calls this date “The Jordan”: 10 Tishri, 11 September AD 26 — “thirty Hebrew years later, to the day” after the birth. Luke writes that Jesus “began to be about thirty years of age” (Luke 3:23).",
   "descriptionDerived": true,
   "video": null,
   "verses": [
    {
     "ref": "Luke 3:21",
     "text": "Now when all the people were baptized, it came to pass, that Jesus also being baptized, and praying, the heaven was opened,"
    },
    {
     "ref": "Luke 3:22",
     "text": "And the Holy Ghost descended in a bodily shape like a dove upon him, and a voice came from heaven, which said, Thou art my beloved Son; in thee I am well pleased."
    },
    {
     "ref": "Luke 3:23",
     "text": "And Jesus himself began to be about thirty years of age, being (as was supposed) the son of Joseph, which was the son of Heli,"
    }
   ],
   "teaching": [
    {
     "from": "guide",
     "marker": "jordan",
     "html": "Guide’s chart: <b>10 Tishri AM 3787 = 11 September AD 26</b>, “thirty Hebrew years later, to the day.” Birth → Jordan = 10,957 days."
    },
    {
     "from": "guide",
     "marker": "jordan",
     "html": "Luke 3:23 is “the phrase Hoehner’s road must stretch” (to 32 or 34)."
    }
   ]
  },
  {
   "id": "tabernacles",
   "kind": "lesson",
   "title": "“That great day”",
   "date": "Mon Oct 17, AD 29 · Tabernacles",
   "dateNote": "Video lesson RL7.1a “The Water”",
   "aliases": [
    "tabernacles",
    "sukkot",
    "that great day",
    "booths"
   ],
   "timelineIds": [
    "jn737",
    "tab29",
    "half",
    "jn714",
    "jn82"
   ],
   "description": "Video lesson RL7.1a, “The Water” (17 minutes), on John 7: “In the last day, that great day of the feast” of Tabernacles, Jesus stood and cried, “If any man thirst, let him come unto me, and drink.” The lesson dates the great day to 21 Tishri — 17 October AD 29, the 7th day of the feast — and traces “rivers of living water” (John 7:38) to Zechariah 14:8 and Jeremiah 2:13 and 17:13.",
   "descriptionDerived": true,
   "video": {
    "kind": "mp4",
    "src": "/videos/rl71a-the-water.mp4",
    "poster": "/videos/rl71a-the-water.jpg",
    "title": "Video lesson RL7.1a “The Water” (17 min)",
    "key": "mp4-rl71a-the-water",
    "lesson": "“The Water” (RL7.1a)"
   },
   "verses": [
    {
     "ref": "John 7:37",
     "text": "In the last day, that great day of the feast, Jesus stood and cried, saying, If any man thirst, let him come unto me, and drink."
    },
    {
     "ref": "John 7:38",
     "text": "He that believeth on me, as the scripture hath said, out of his belly shall flow rivers of living water."
    },
    {
     "ref": "John 7:39",
     "text": "(But this spake he of the Spirit, which they that believe on him should receive: for the Holy Ghost was not yet given; because that Jesus was not yet glorified.)"
    },
    {
     "ref": "Leviticus 23:36",
     "text": "Seven days ye shall offer an offering made by fire unto the LORD: on the eighth day shall be an holy convocation unto you; and ye shall offer an offering made by fire unto the LORD: it is a solemn assembly; and ye shall do no servile work therein."
    },
    {
     "ref": "Zechariah 14:8",
     "text": "And it shall be in that day, that living waters shall go out from Jerusalem; half of them toward the former sea, and half of them toward the hinder sea: in summer and in winter shall it be."
    },
    {
     "ref": "Jeremiah 2:13",
     "text": "For my people have committed two evils; they have forsaken me the fountain of living waters, and hewed them out cisterns, broken cisterns, that can hold no water."
    },
    {
     "ref": "Jeremiah 17:13",
     "text": "O LORD, the hope of Israel, all that forsake thee shall be ashamed, and they that depart from me shall be written in the earth, because they have forsaken the LORD, the fountain of living waters."
    },
    {
     "ref": "John 7:2",
     "text": "Now the Jews’ feast of tabernacles was at hand."
    },
    {
     "ref": "Leviticus 23:34",
     "text": "Speak unto the children of Israel, saying, The fifteenth day of this seventh month shall be the feast of tabernacles for seven days unto the LORD."
    },
    {
     "ref": "John 1:14",
     "text": "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth."
    },
    {
     "ref": "John 7:6",
     "text": "Then Jesus said unto them, My time is not yet come: but your time is alway ready."
    },
    {
     "ref": "John 7:8",
     "text": "Go ye up unto this feast: I go not up yet unto this feast; for my time is not yet full come."
    },
    {
     "ref": "John 7:30",
     "text": "Then they sought to take him: but no man laid hands on him, because his hour was not yet come."
    }
   ],
   "teaching": [
    {
     "from": "video",
     "marker": "half",
     "html": "Video lesson RL7.1a “The Water” opens “the seventh and last half-year” of the ministry: <b>176 days</b> from Tabernacles to the cross. It counts 2 days at Tabernacles, 1 at Dedication and 8 at the end, with <b>67 days</b> of silence between Tabernacles and Dedication and <b>99 days</b> between Dedication and the final 8."
    },
    {
     "from": "video",
     "marker": "tab29",
     "html": "Video: <i>skēnopēgia</i> (“tabernacles”, John 7:2) occurs only once in the New Testament. The video links it with <i>eskēnōsen</i>, “dwelt” (literally “tabernacled”), in John 1:14. That link is the video’s interpretation."
    },
    {
     "from": "video",
     "marker": "tab29",
     "html": "Video: John 7 is “the most dangerous chapter”. <i>Apokteinō</i>, “to kill”, is used 12× in John, 4 of them in chapter 7; <i>piazō</i>, “to seize”, 3×, all here."
    },
    {
     "from": "video",
     "marker": "tab29",
     "html": "Video: Jesus speaks of his <i>kairos</i>, “time” (7:6, 8); the narrator speaks of his <i>hōra</i>, “hour” (7:30)."
    },
    {
     "from": "video",
     "marker": "jn737",
     "html": "Video: the great day is <b>21 Tishri AM 3790 = 17 October AD 29</b>, the 7th day of the feast."
    },
    {
     "from": "video",
     "marker": "jn737",
     "html": "Video: the water-drawing from Siloam (Mishnah Sukkah 4:9; 4:1; 4:8), compiled about AD 200, so second-hand history. Which day is “the last day, that great day”, the 7th or the 8th, is left <b>unresolved</b>: Sukkah 4:1 has the water rite for seven days, while 4:8 calls the 8th “the last festival day”."
    },
    {
     "from": "video",
     "marker": "jn737",
     "html": "Video: “rivers of living water” (7:38). A Greek search leads to Zechariah 14:8. The Hebrew <i>meqor mayim chayyim</i>, “fountain of living waters”, is in Jeremiah 2:13 and 17:13, which the Septuagint renders “fountain of life”. The video argues John is translating from the Hebrew."
    }
   ]
  },
  {
   "id": "passover",
   "kind": "lesson",
   "title": "Passover · The Cross",
   "date": "Wed Apr 5, AD 30",
   "dateNote": "Professor Zac’s guide",
   "aliases": [
    "passover",
    "the cross",
    "cross",
    "crucifixion"
   ],
   "timelineIds": [
    "cross",
    "jn131",
    "jn1828",
    "jn1942"
   ],
   "description": "On the guide’s chart the cross falls on 14 Nisan — Wednesday 5 April AD 30, “the preparation of the passover” (John 19:14). The guide notes that the weekday is computation, not text: the Wednesday comes from the fixed Hebrew calendar.",
   "descriptionDerived": true,
   "video": null,
   "verses": [
    {
     "ref": "John 19:30",
     "text": "When Jesus therefore had received the vinegar, he said, It is finished: and he bowed his head, and gave up the ghost."
    },
    {
     "ref": "John 19:14",
     "text": "And it was the preparation of the passover, and about the sixth hour: and he saith unto the Jews, Behold your King!"
    }
   ],
   "teaching": [
    {
     "from": "guide",
     "marker": "cross",
     "html": "Guide’s chart: <b>14 Nisan AM 3790 = Wednesday 5 April AD 30</b>. “The weekday is computation, not text. The Wednesday comes from the fixed Hebrew calendar, which was arranged in the fourth century. No observational reconstruction of that spring produces a Wednesday.”"
    },
    {
     "from": "guide",
     "marker": "cross",
     "html": "“Every reading of the crescent still lands the fourteenth of Nisan in AD 30.” “Accept the 23 March crescent and the fourteenth falls on Friday 7 April.”"
    }
   ]
  },
  {
   "id": "resurrection",
   "kind": "lesson",
   "title": "He is risen",
   "date": "Sat Apr 8 – Sun Apr 9, AD 30",
   "dateNote": "72 hours from the Wednesday burial (the guide gives no hour)",
   "aliases": [
    "resurrection",
    "he is risen",
    "risen",
    "firstfruits",
    "first fruits"
   ],
   "timelineIds": [
    "three",
    "jn201",
    "jn2019",
    "high"
   ],
   "description": "The sign of Jonah: “three days and three nights in the heart of the earth” (Matthew 12:40). The guide’s Wednesday gives “three days and three nights, evening to evening,” which it calls “the cleanest arrangement available for the sign of Jonah.” The date here is counted 72 hours from the Wednesday burial; the guide gives no hour.",
   "descriptionDerived": true,
   "video": null,
   "verses": [
    {
     "ref": "Matthew 28:6",
     "text": "He is not here: for he is risen, as he said. Come, see the place where the Lord lay."
    },
    {
     "ref": "Matthew 12:40",
     "text": "For as Jonas was three days and three nights in the whale’s belly; so shall the Son of man be three days and three nights in the heart of the earth."
    },
    {
     "ref": "John 20:1",
     "text": "The first day of the week cometh Mary Magdalene early, when it was yet dark, unto the sepulchre, and seeth the stone taken away from the sepulchre."
    }
   ],
   "teaching": [
    {
     "from": "guide",
     "marker": "high",
     "html": "The guide’s Wednesday gives “three days and three nights, evening to evening, with two sabbaths and a working day between them”: the festival sabbath of 15 Nisan (Thu), a working day (Fri 7 Apr, 16 Nisan), then the weekly Sabbath (Sat 8 Apr, 17 Nisan)."
    },
    {
     "from": "guide",
     "marker": "three",
     "html": "“That is the cleanest arrangement available for the sign of Jonah.” “Three days and three nights in the heart of the earth is Text … If the day is ever shown to be otherwise, the saying does not fall; the reconstruction of it does.”"
    }
   ]
  },
  {
   "id": "pentecost",
   "kind": "lesson",
   "title": "Pentecost",
   "date": "Sun May 28, AD 30",
   "dateNote": "Counted 50 days (the guide doesn’t give this date)",
   "aliases": [
    "pentecost",
    "shavuot",
    "weeks"
   ],
   "timelineIds": [
    "pent",
    "asc"
   ],
   "description": "“When the day of Pentecost was fully come, they were all with one accord in one place” (Acts 2:1). The site shows it with Leviticus 23:15–16, where Israel is told to “number fifty days.” The guide doesn’t give this date; it is counted 50 days.",
   "descriptionDerived": true,
   "video": null,
   "verses": [
    {
     "ref": "Acts 2:1",
     "text": "And when the day of Pentecost was fully come, they were all with one accord in one place."
    },
    {
     "ref": "Leviticus 23:15",
     "text": "And ye shall count unto you from the morrow after the sabbath, from the day that ye brought the sheaf of the wave offering; seven sabbaths shall be complete:"
    },
    {
     "ref": "Leviticus 23:16",
     "text": "Even unto the morrow after the seventh sabbath shall ye number fifty days; and ye shall offer a new meat offering unto the LORD."
    }
   ],
   "teaching": []
  }
 ]
};
